### ISSUE TITLE
Unable to use javakdb maven dependency in Pom - getting Failed to read artifact descriptor for com.kx:javakdb:jar:2.0. 

### ISSUE THREAD

**Issue by codewithsugi** [KxSystems/javakdb#86]
Unable to use the maven dependency in Pom - getting Failed to read artifact descriptor for com.kx:javakdb:jar:2.0. The following artifacts could not be resolved: com.kx.multi:JavaKdbModules:pom:2.0 )absent.

I am having the below dependency in my pom.xml 
<dependency>
    <groupId>com.kx</groupId>
    <artifactId>javakdb</artifactId>
    <version>2.0</version>
</dependency>

Link --> https://central.sonatype.com/artifact/com.kx/javakdb

and settings.xml (followed this only)--> https://central.sonatype.org/consume/consume-apache-maven/ 

in your settings.xml we are referring  <url>https://repo1.maven.org/maven2</url> but actually the jar is available in https://repo.maven.apache.org/maven2/com/kx/. I have updated my settings xml but still I am facing the same issue. 

And I hope the minimum requirement to use this jar is Java 1.8 but I am using java 11.

Can you guys please have a look and let me know the correct dependency to use it in our projects?

**Comment by sshanks-kx** [comment]
This bit `com.kx.multi:JavaKdbModules:pom:2.0 absent.` about missing pom has been rectified & should be there now if you could try again. Sorry.

**Comment by codewithsugi** [comment]
Hi @sshanks-kx , Thanks for your quick response. Yes now there is no such error and its loading properly with this settings (https://central.sonatype.org/consume/consume-apache-maven/)

**Comment by sshanks-kx** [comment]
Closing now as appears to be ok. Thanks for letting us know.
